server:
  port: 18082
spring:
  application:
    name: user-consumer
  cloud:
    stream:
      kafka:
        binder:
          brokers: 192.168.10.35:9092
          zk-nodes: 192.168.10.35:2181
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:18081/eureka