spring:
  application:
    name: user-service
server:
  port: 9090
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
  endpoint:
    hystrix:
      stream:
        enabled: true
