spring:
  application:
    name: user-service
server:
  port: 9090
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
  endpoint:
    hystrix:
      stream:
        enabled: true
eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:8080/eureka
